server:
  port: ${PORT:8081}
spring:
  application:
    name: notifs
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: https://fgsc-eureka-server.herokuapp.com/eureka
#      http://user:password@url/eureka
security:
  user:
    password: ${eureka.password}
---
eureka:
  instance:
    hostname: fgsc-rsocket-broker.herokuapp.com
    nonSecurePort: 80
    prefer-ip-address: true
    app-group-name: fgsc
    appname: notifs
  password: ${USER_PASSWORD:password}
#security:
#  user:
#    password: ${eureka.password}
